packages:
  - 'src/*'
  - 'src/vendor/*'
  - 'desktop'
allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@nefevcore/abap-adt-dsh-plugin@0.6.0'
  - '@nefevcore/abap-adt-mock@0.6.0 || 0.7.0 || 0.7.1 || 0.7.2'
  - '@nefevcore/abap-adt-protocol@0.6.0 || 0.7.0 || 0.7.1 || 0.7.2'
  - '@nefevcore/abap-adt-core@0.7.0 || 0.7.1 || 0.7.2'
